config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:show, :edit, :index, :update, :create, :destroy] do
    # いいね機能
    resource :favorites, only: [:create, :destroy]
    # コメント機能
    resources :book_comments, only: [:create, :destroy]
  end
  # フォロー機能
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/follows' => "users#follows"
  get 'users/:id/followers' => "users#followers"

  # 検索機能
  get 'search' => 'searches#search'
  # チャット
  resources :chats, only: [:show, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  has_many :books, dependent: :destroy

  # def email_required?
  #   false
  # end
  # def will_save_change_to_email?
  #   false
  # end

  # コメント機能
  has_many :book_comments, dependent: :destroy
  # いいね機能
  has_many :favorites, dependent: :destroy

  # フォロー機能
  # ========自分がフォローしているユーザーとの関連======
  # ①中間モデルRelationship
  has_many :relationships
  # ②M対Nの相手NのUserモデル
  has_many :followings, through: :relationships, source: :follow
  # ========自分がフォローされるユーザーとの関連========
  # ①中間モデルRelationship
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # ②M対Nの相手NのUserモデル
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user # 自分以外の人であれば下記実行
      relationships.find_or_create_by(follow_id: other_user.id) # フォロー済みならRelation を返し、フォローしてなければフォロー関係を保存(create = new + save)する
    end
  end

  def unfollow(other_user)
    relationship = relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship # relationship が存在すれば(=フォロー済みなら) destroy
  end

  # 自分はother_userをフォローしてるか？
  def following?(other_user)
    followings.include?(other_user)
  end

  # 検索機能
  def self.search(search, word)
    if search == "forward_match"
      User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      User.where("name LIKE?", "%#{word}")
    elsif search == "perfect_match"
      User.where("name =?", "#{word}")
    elsif search == "partial_match"
      User.where("name LIKE?", "%#{word}%")
    else
      User.all
    end
  end

  # 住所検索（JpPrefecture gem)
  validates :postal_code, presence: true, length: { is: 7 }, numericality: { only_integer: true }
  validates :city, presence: true
  validates :street, presence: true

  include JpPrefecture
  jp_prefecture :prefecture_code
  # postal_codeからprefecture_nameに変換するメソッドを用意
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  # prefecture_name2都道府県名を代入したらprefecture_codeに反映させるメソッド
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # GooleMap導入のため緯度経度取得(本来不要)
  # def address
  #   "%s %s" % [postal_code, city, street]
  # end

  # 上記と同じ（下記はGH掲載）
  # def address
  #   [postal_code,city,street].compact.join(', ')
  # end
  # 下記不要
  # geocoded_by self.address
  # after_validation :geocode, if: :address_changed?

  # チャット
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  #  def create
  #   super
  #   ThanksMailer.thanks_mail(@user).deliver_now
  #  end

  def create
    build_resource(sign_up_params)
    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        ThanksMailer.thanks_mail(current_user).deliver_now # この一文追加
        # DailyMailer.daily_mail.deliver_now
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # private
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # deviseのメソッド:ログインしてなかったらログイン画面に返す（URL直打ちも不可）
  before_action :authenticate_user!
  # current_user以外がedit,updateできないようにする（URL直打ちも不可）
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :set_user, only: [:show, :edit, :update, :follows, :followers]

  def show
    @book = Book.new
    @books = @user.books
    # binding.pry
  end

  def index
    @users = User.all
    @user = User.find_by(id: current_user.id)
    @book = Book.new
  end

  def edit
    # ensure_correct_userがあるのでset_userで問題なく、下記不要
    # @user = User.find_by(id: current_user.id)
  end

  def update
    # ensure_correct_userがあるのでset_userで問題なく、下記不要
    # @user = User.find_by(id: current_user.id)
    if @user.update(user_params)
      flash[:user_update] = ""
      redirect_to user_path(@user.id)
    else
      render :edit
   end
  end

  # フォロー機能
  def follows
  end

  def followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :postal_code, :prefecture_code, :city, :street)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    if current_user.id != params[:id].to_i
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td>
        <%= attachment_image_tag user, :profile_image, size: "40x40", format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
        </td>
        <td><%=user.name %></td>
        <td>フォロー数：<%= user.followings.count %></td>
        <td>フォロワー数：<%= user.followers.count %></td>
        <td><%= render 'relationships/follow_button', user: user %></td>
        <td><%=link_to"Show", user_path(user.id),class:"users_show" %></td>
      </tr>
      <% end %>
  </tbody>
</table> 

app/views/users/_info.html.erb
  <table class="table">
    <tbody>
      <tr>
        <%= attachment_image_tag user, :profile_image, size: "100x100",format: 'jpeg', class: "profile-img", fallback: "no_image.jpg" %>
      </tr> 
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <%# フォロー機能 %>
      <tr>
        <th>follows</th>
        <th><%= link_to "/users/#{user.id}/follows",class:"books_show" do %><%= user.followings.count %><% end %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to "/users/#{user.id}/followers",class:"books_show" do %><%= user.followers.count %><% end %></th>
      </tr>
    </tbody>
  </table>

  <% if current_user != user %>
  <%# フォローボタン %>
  <div class="row">
      <%= render 'relationships/follow_button', user: user %>
  </div>  
  <%# チャット %>
    <%= link_to 'chatを始める', chat_path(user.id)%>
  <% end %>

  <%# ユーザー編集ボタン %>
  <div class="row">
    <%= link_to "",edit_user_path(user.id), class:"col-xs-12 btn btn-default glyphicon glyphicon-wrench" %>
  </div>

app/views/users/edit.html.erb
<div class="container main-container">
  <p id="notice"></p>
  <h2>User info</h2>
  <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true, autocomplete: "name",class:"name",id:"user_name" %>
      </div>    

      <div class="firld">
        <%= f.label :image %><br />
        <%= f.attachment_field :profile_image,class: "user-edit-form" %>
      </div>         

      <div class="field">
        <%= f.label :introduction %><br />
        <%= f.text_area :introduction, autofocus: true,class:"introduction" %>
      </div>    

      <%# #住所検索（JpPrefecture gem) %>
      <div class="field">
        <%= f.label :postal_code %><br />
        <%= f.text_field :postal_code, autofocus: true, class: "postal_code", id: "address_zipcode" %>
      </div>

      <div class="field">
        <%= f.label :prefecture_code %><br>
        <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :name, :name, class: "address" %>
      </div>

      <div class="field">
        <%= f.label :city %><br>
            <%= f.text_field :city, autofocus: true, class: "address", id:"address_city" %>
      </div>
      <div class="field">
        <%= f.label :street %><br>
        <%= f.text_field :street, autofocus: true, class: "address_street" %>
      </div>
      <%= f.submit "Update User",data: { disable_with: "Sign up" } %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="container">
  <% if @user.followers.count > 0 %>
    <h2>Follower Users</h2>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @user.followers.each do |followers| %>
          <tr>
            <td>
            <%= attachment_image_tag followers, :profile_image, size: "40x40", format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
            </td>
            <td><%=followers.name %></td>
            <td>フォロー数：<%= followers.followings.count %></td>
            <td>フォロワー数：<%= followers.followers.count %></td>
            <td><%= render 'relationships/follow_button', user: followers %></td>
            <td><%=link_to"Show", user_path(followers.id),class:"followers_show" %></td>
          </tr>
        <% end %>
      </tbody>
    </table> 
  <% else %>
    <h2>No Follower User</h2> 
  <% end %>
</div>  

app/views/users/follows.html.erb
  <div class="container">
    <% if @user.followers.count > 0 %>
      <h2>Follow Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      
        <tbody>
          <% @user.followings.each do |follows| %>
            <tr>
              <td>
              <%= attachment_image_tag follows, :profile_image, size: "40x40", format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
              </td>
              <td><%=follows.name %></td>
              <td>フォロー数：<%= follows.followings.count %></td>
              <td>フォロワー数：<%= follows.followers.count %></td>
              <td><%= render 'relationships/follow_button', user: follows %></td>
              <td><%=link_to"Show", user_path(follows.id),class:"follows_show" %></td>
            </tr>
          <% end %>
        </tbody>
      </table> 
      <% else %>
        <h2>No Follow User</h2> 
      <% end %>
  </div>  

app/views/users/index.html.erb
<div class="container main-container">
  <p id="notice"></p>
  <div class="row">
    <!-- 左側 上-->
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <!-- 左側 下-->
      <h2>New book</h2>
      <%= render 'books/create_book_form', book: @book %>
    </div>
    <!-- 右側 -->
    <div class="col-xs-9">
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>  
  </div>
</div>

app/views/users/show.html.erb
<div class="container main-container">
  <p id="notice"></p>

  <div class="row">
    <!-- 左側 上 -->
    <div class="col-xs-3">
      <h2>User info</h2>
        <%= render 'info', user: @user,now: ''%>
      <!-- 左側 下 -->
      <h2>New book</h2>
      <%= render 'books/create_book_form', book: @book %>
    </div>
  
    <!-- 右側 -->
    <div class="col-xs-9">
      <%= render 'books/books', books: @books %>
    </div>
  </div>    
  
  <!-- 下（MAP)(BEM記法） -->
  <% if @user == current_user %>
    <div class="row">
      <div class="col-xs-12 map">
          <h2 class="map__head">Your Map</h2>
          <p class="map__adress">住所： 〒<%= @user.postal_code %>&emsp;<% @user.prefecture_code %>&ensp;<%= @user.city %>&ensp;<%= @user.street%></p>
          <%# Google マップ %>
          <div id='map' class="<%= @user.prefecture_code.to_s + @user.city + @user.street %> map__google-map">
      </div>
    </div>
  <% end %>
</div>

<%# Google マップ(JS)  %>
<script sec="javascripts/address_map.js"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>
<%# <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC7wALtCD2-jLMnFfdOUaxxfvOtA_wKqs8&callback=initMap" async defer></script> %>

 


        
            
          