config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:show, :edit, :index, :update, :create, :destroy] do
    # いいね機能
    resource :favorites, only: [:create, :destroy]
    # コメント機能
    resources :book_comments, only: [:create, :destroy]
  end
  # フォロー機能
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/follows' => "users#follows"
  get 'users/:id/followers' => "users#followers"

  # 検索機能
  get 'search' => 'searches#search'
  # チャット
  resources :chats, only: [:show, :create]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 199 }
  # いいね機能
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  # コメント機能
  has_many :book_comments, dependent: :destroy
  # 検索機能
  def self.search(search, word)
    if search == "forward_match"
      @books = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @books = Book.where("title LIKE?", "%#{word}")
    elsif search == "perfect_match"
      @books = Book.where("title =?", "#{word}")
    elsif search == "partial_match"
      @books = Book.where("title LIKE?", "%#{word}%")
    else
      @books = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # deviseのメソッド:ログインしてなかったらログイン画面に返す（URL直打ちも不可）
  before_action :authenticate_user!
  # current_user以外がedit,updateできないようにする（URL直打ちも不可）
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.find_by(id: current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    # binding.pry
    @book.user_id = current_user.id
    if @book.save
      flash[:create] = ""
      redirect_to book_path(@book.id)
    else
      @user = User.find_by(id: current_user.id)
      @books = Book.all
      flash.now[:alert_create] = ""
      render :index
    end
  end

  def show
    @create_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
  end

  def update
    if @book.update(book_params)
      flash[:book_update] = ""
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :user)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
  <% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <span class="glyphicon glyphicon-heart" aria-hidden="true"><%= book.favorites.count %></span>
    <% end %>
  <% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"><%= book.favorites.count %></span>
    <% end %>
  <% end %>

app/views/books/_books.html.erb
<h2>Books</h2>
<table class="table table-hover table-inverse">
  <thead>
    <tr> 
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to users_path(book.user) do %>
          <%= attachment_image_tag book.user, :profile_image, size: "40x40", format: 'jpeg', class: "pull-left profile-img", fallback: "no_image.jpg" %>
          <% end %>
        </td>
        <td>
          <%= link_to book_path(book.id),class:"books_show" do %><%= book.title %><% end %>
        </td>
        <td><%= book.body %></td>
        <%# いいね %>
        <td class="book_<%= book.id %>">
          <%= render 'books/book', book: book %>
        </td>
        <%# コメント %>
        <td>コメント数：<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_create_book_form.html.erb
<%= form_for(book) do |f| %>
    <div class="field row ">
      <%= f.label :title %><br />
      <%= f.text_field :title, autofocus: true, class:"col-xs-12 book_title",id:"book_title" %>
    </div>

    <div class="field row">
      <%= f.label :body,"Opinion" %><br />
      <%= f.text_area :body, autofocus: true,class:"col-xs-12 book_body",id:"book_body" %>
    </div>       

    <div class="actions row">
      <%= f.submit "Create Book",class:"btn btn-primary col-xs-12" ,data: { disable_with: "Sign up" } %>
    </div>
<% end %>

app/views/books/edit.html.erb
<div class="container main-container">
  <p id="notice"></p>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>
      <%= render 'create_book_form', book: @book %>
      <div class="link">
        <%=link_to "Show",book_path(@book.id),class:"show" %>&ensp;|&ensp;<%=link_to "Back",books_path, class:"back" %>
      </div>
    </div>
    <div class="col-md-3">
    </div>
</div>

app/views/books/index.html.erb
<div class="container main-container">
  <p id="notice"></p>
  <div class="row">
    <!-- 左側 上-->
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>

      <!-- 左側 下-->
      <h2>New book</h2>
      <%= render 'create_book_form', book: @book %>       
    </div>

    <%# 右側 %>
    <div class="col-xs-9">
      <%= render 'books', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container main-container">
  <p id="notice"></p>
  <div class="row">
    <!-- 左側 上-->
    <div class="col-xs-3">
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
    <!-- 左側 下-->
      <h2>New book</h2>
      <%= render 'create_book_form', book: @create_book %>
    </div>
  <%# 右側 %>
    <div class="col-xs-9 container">
      <h2>Book detail</h2>
      <table class="table">
        <thead>
          <tr> 
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <div>
                <%=link_to user_path(@book.user.id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, size: "100x100", format: 'jpeg', class: " profile-img", fallback: "no_image.jpg", size:'50x50' %>
                <% end %>
              </div>
              <div>
                <%=link_to @book.user.name, user_path(@book.user.id), class: "text-muted user-name" %>
              </div> 
            </td>
            <td> <%= link_to book_path(@book.id),class:"books-show" do %><%= @book.title %><% end %></td>
            <td><%= @book.body %></td>

            <% if @book.user == current_user %>
              <td>
                <%= link_to "Edit",edit_book_path(@book.id),class:"btn-sm btn-success" %>
              </td>
              <td>
                <%= link_to "Destroy", book_path(@book.id), method: :delete, class:"btn-sm btn-danger",data:{confirm:"本当に消しますか？"} %>
              </td>
            <% end %>
            <%# いいね %>
            <td class="book_<%= @book.id %>">
              <%= render 'books/book', book: @book %>
            </td>
          </tr>
        </tbody>
      </table>
      <%# コメント一覧 %>
      <ul class="comments_area row">
        <%= render 'book_comments/index', book: @book %>
      </ul>
      <%# コメント入力 %>
      <%= render 'book_comments/form',{ book: @book, book_comment: @book_comment } %>
    </div>
  </div> 
</div>