config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'home/about'
  devise_for :users
  resources :users, only: [:show, :edit, :index, :update]
  resources :books, only: [:show, :edit, :index, :update, :create, :destroy] do
    # いいね機能
    resource :favorites, only: [:create, :destroy]
    # コメント機能
    resources :book_comments, only: [:create, :destroy]
  end
  # フォロー機能
  resources :relationships, only: [:create, :destroy]
  get 'users/:id/follows' => "users#follows"
  get 'users/:id/followers' => "users#followers"

  # 検索機能
  get 'search' => 'searches#search'
  # チャット
  resources :chats, only: [:show, :create]
end

app/views/layouts/_error_messages.html.erb
<head>
  <style>
    
    .error-prohibited,.alert{
      color:#FD1716;
    }
    .alert ul{
      list-style-type: disc;
      font-size: 13px;
      line-height: 18px;
      margin-left: 33px;
    }
    .error-prohibited{
      font-size: 24px;
    }
  </style>
</head>

<body>
  <% if model.errors.any? %>
    <div class="error_explanation">
      <h2 class="error-prohibited">
        <%= pluralize(model.errors.count, "error") %> prohibited this user from being saved:
      </h2>
      <div class="alert">
        <ul>
          <% model.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</body>

app/views/layouts/_flash_messages.html.erb
<head>
  <style>
  /* create,user_update,book_update */
    .create,.user_update,.book_update{
      margin:10px 0;
      font-size: 13px;
      line-height: 18px;
    }
  /* alert_cretate */
    .alert_create{
      color:#FD1716;
    }
    .alert_create ul{
      list-style-type: disc;
      font-size: 13px;
      line-height: 18px;
      margin-left: 33px;
    }
    /* divaseのflashメッセージ */
    .flash_alert {
      color:red;
    }
    .flash_notice {
      color: green;      
    }
  </style>
</head>

<body>
  <% flash.each do |message_type, message| %>

    <%# divaseのflashメッセージ %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "flash flash_#{key}") %>
    <% end %>


    <%# ログイン中 %>
    <% if flash[:create] %>
      <div class="create">
        <%= message %>
        <p>You have creatad book successfully.</p>
      </div>
    <% end %>

    <% if flash[:alert_create] %>
      <div class="alert_create">
        <%= message %>
        <h3><%= pluralize(@book.errors.count, "error") %> errors prohibited this obj from being saved:</h3>
        <ul>
          <li>Title can't be blank</li>
          <li>Body can't be blank</li>
        </ul>
      </div>
    <% end %>

    <% if flash[:user_update] %>
      <div class="user_update">
        <%= message %>
        <p>You have updatad user successfully.</p>
      </div>
    <% end %>


    <% if flash[:book_update] %>
      <div class="book_update">
        <%= message %>
        <p>You have updated book successfully.</p>
      </div>
    <% end %>

  <% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse ">
      <div class="container">
        <nav class="nav navbar-brand navbar-left">
          <span class="bookers">Bookers</span>
        </nav>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                  <li class="">
                    <%= link_to user_path(current_user)  do %><i class="glyphicon glyphicon-home home"></i>&emsp;Home<% end %>
                  </li>
                  <li>
                    <%= link_to users_path do %><i class="glyphicon glyphicon-user users"></i>&emsp;Users<% end %>
                  </li>
                  <li>
                    <%= link_to books_path do %><i class="glyphicon glyphicon-book books"></i>&emsp;Books<% end %>
                  </li>
                  <li>
                    <%= link_to destroy_user_session_path, method: :delete do %><i class="glyphicon glyphicon-log-out logout"></i>&emsp;logout<% end %>
                  </li>
                <% else %>
                  <li class="">
                  <%= link_to root_path do %><i class="glyphicon glyphicon-home home"></i>&emsp;Home<% end %>
                  </li>
                  <li class="">
                    <%= link_to home_about_path do %><i class="glyphicon glyphicon-link about"></i>&emsp;About<% end %>
                  </li>
                  <li class="">
                    <%= link_to new_user_registration_path do %><i class="glyphicon glyphicon-edit sign_up"></i>&emsp;Sign up<% end %>
                  </li>
                  <li class="">
                    <%= link_to new_user_session_path do %><i class="glyphicon glyphicon-log-in sign_in"></i>&emsp;login<% end %>
                  </li>
                <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <main>
      <%# 検索フォーム %>
      <% if user_signed_in? %>
        <div class="container search">
          <%= form_tag(search_path, method: :get) do %>
            <%= select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']]) %>
            <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
            <%= text_field_tag (:word) %>
            <%= submit_tag "検索" %>
          <% end %>
        </div>
      <% end %>
      <%# フラッシュメッセージ %>
      <div class="container flash">
        <%= render 'layouts/flash_messages' %>
      </div>
      <%# 各ページ本体 %>
      <%= yield %>
    </main>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-xs-3 col-xs-offset-9">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer> 

  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Bookers
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.navbar.navbar-fixed-top.navbar-inverse
      .container
        %nav.nav.navbar-brand.navbar-left
          %span.bookers Bookers
        %nav
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                = link_to user_path(current_user)  do
                  %i.glyphicon.glyphicon-home.home>
                   Home
              %li
                = link_to users_path do
                  %i.glyphicon.glyphicon-user.users>
                   Users
              %li
                = link_to books_path do
                  %i.glyphicon.glyphicon-book.books>
                   Books
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %i.glyphicon.glyphicon-log-out.logout>
                   logout
            - else
              %li
                = link_to root_path do
                  %i.glyphicon.glyphicon-home.home>
                   Home
              %li
                = link_to home_about_path do
                  %i.glyphicon.glyphicon-link.about>
                   About
              %li
                = link_to new_user_registration_path do
                  %i.glyphicon.glyphicon-edit.sign_up>
                   Sign up
              %li
                = link_to new_user_session_path do
                  %i.glyphicon.glyphicon-log-in.sign_in>
                   login
    %main
      - if user_signed_in?
        .container.search
          = form_tag(search_path, method: :get) do
            = select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']])
            = select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])
            = text_field_tag (:word)
            = submit_tag "検索"
      .container.flash
        = render 'layouts/flash_messages'
      = yield
    %footer
      .container
        .row
          .col-xs-3.col-xs-offset-9
            %p CopyRight Infratop.inc

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Bookers
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header.navbar.navbar-fixed-top.navbar-inverse
      .container
        nav.nav.navbar-brand.navbar-left
          span.bookers
            | Bookers
        nav
          ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              li
                = link_to user_path(current_user)  do
                  i.glyphicon.glyphicon-home.home
                  |  Home
              li
                = link_to users_path do
                  i.glyphicon.glyphicon-user.users
                  |  Users
              li
                = link_to books_path do
                  i.glyphicon.glyphicon-book.books
                  |  Books
              li
                = link_to destroy_user_session_path, method: :delete do
                  i.glyphicon.glyphicon-log-out.logout
                  |  logout
            - else
              li
                = link_to root_path do
                  i.glyphicon.glyphicon-home.home
                  |  Home
              li
                = link_to home_about_path do
                  i.glyphicon.glyphicon-link.about
                  |  About
              li
                = link_to new_user_registration_path do
                  i.glyphicon.glyphicon-edit.sign_up
                  |  Sign up
              li
                = link_to new_user_session_path do
                  i.glyphicon.glyphicon-log-in.sign_in
                  |  login
    main
      - # 検索フォーム
      - if user_signed_in?
        .container.search
          = form_tag(search_path, method: :get) do
            = select_tag 'range' ,options_for_select([['---選択してください---', ''], ['User', '1'], ['Book', '2']])
            = select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])
            = text_field_tag (:word)
            = submit_tag "検索"
      - # フラッシュメッセージ
      .container.flash
        = render 'layouts/flash_messages'
      - # 各ページ本体
      = yield
    footer
      .container
        .row
          .col-xs-3.col-xs-offset-9
            p
              | CopyRight Infratop.inc